Form footer
Gunjuzone/My-Portfolio pull request #3
Opened 2021-06-15 21:12 UTC by Gunjuzone

In this pull request, form and footer are added to my portfolio.

2021-06-15 22:05 UTC, Davidosky007 requested changes
Hi, @Gunjuzone, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
* I suggest you make your pull request have a descriptive title telling what changes were made inside.
* And a short summary describing introduced changes in more detail.
* I left you comments below please make the necessary changes 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-06-15 22:05 UTC, Davidosky007 commented on index.html
> +    <form action="https://formspree.io/f/mleanrp" method="POST">
I suggest you check the form id properly i get this when i submit: 
![Screenshot (75)](https://user-images.githubusercontent.com/52497246/122128207-410a2980-ce2c-11eb-9fb3-d53b790fe1b4.png)

2021-06-15 22:05 UTC, Davidosky007 commented on index.html
> +    </footer>
This section is different from the original design template please fix it 🙏 
* Yours:
![Screenshot (76)](https://user-images.githubusercontent.com/52497246/122128758-f0df9700-ce2c-11eb-9711-36f3bbd6c764.png)

* Figma Design:
![Screenshot (77)](https://user-images.githubusercontent.com/52497246/122128789-fb9a2c00-ce2c-11eb-97cf-2ab8a62e0957.png)

2021-06-16 00:51 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi @Gunjuzone , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

## Something to include ☑️ 
- Your responsive is good, but when I see the desktop size it looks like this, I kindly invite you to change this.
![image](https://user-images.githubusercontent.com/20563252/122141406-de586400-ce12-11eb-8b4e-b58597673371.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-16 09:44 UTC, merged